### ISSUE TITLE
Error with NuxtJS + SSR

### ISSUE THREAD

**Issue by akaNightmare** [chenfengjw163/vue-json-viewer#11]
Uncaught TypeError: Super expression must either be null or a function, not undefined

**Comment by akaNightmare** [comment]
I believe it's related to the https://github.com/zenorocha/clipboard.js/issues/570

**Comment by chenfengjw163** [comment]
Not necessarily, this library does not support ssr, I am trying to support it, please wait a moment.

**Comment by akaNightmare** [comment]
@chenfengjw163 it would be great, I need it ASAP ;)

**Comment by chenfengjw163** [comment]
Solved, you can update to 2.1.3 first:
1. In the component
``` js
import JsonViewer from 'vue-json-viewer/ssr'; 
```
2. And load css separately
```js
import 'vue-json-viewer/style.css';
```
I will update the documentation later.

**Comment by chenfengjw163** [comment]
@akaNightmare

**Comment by akaNightmare** [comment]
@chenfengjw163 thanks a lot!

**Comment by akaNightmare** [comment]
@chenfengjw163  unfortunately had the same error as before 2.1.3, I am pretty sure that the error is related to the https://github.com/zenorocha/clipboard.js/issues/570, maybe need to upgrade clipboard version to 2.0.4?

**Comment by chenfengjw163** [comment]
I think this error may not be related to clipboardjs. This error comes from the _inherits function of babeljs, may be caused by other parts of your project. 
It doesn't matter, I have upgraded to clipboard@2.0.4 and removed the source code of the clipboard from the compiled code to avoid duplicates with the clip referenced by the project. 
Reinstall the latest version of vue-json-viewer, the clipboard will be installed into node_modules as a dependency package.
@akaNightmare

**Comment by akaNightmare** [comment]
@chenfengjw163 It works. Thanks again)
